PostIT/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('page3.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

page3/urls.py
from unicodedata import name
from django.urls import path
from . import views
# from .views import HomeView

urlpatterns = [
    #     path('', views.home, name='home-page'),
    path('', views.home_timeline, name='home-page'),
    path('', views.home_timeline, name='expanded-post-page'),
    path('upload_reply/<int:pk>',
         views.upload_reply, name='upload_reply'),

    #     path('post/<int:post_id>', views.post_details, name='post-page'),
    path('add_post', views.add_post, name='add-post'),
    path('add_image_post', views.add_image_post, name="add-image-post"),
    path('add_video_post', views.add_video_post, name="add-video-post"),
    path('post/edit/<int:post_id>', views.edit_post, name='edit-post'),
    path('post/edit_images/<int:post_id>',
         views.edit_image_post, name='edit-image-post'),
    path('post/edit_video/<int:post_id>',
         views.edit_video_post, name='edit-video-post'),
    path('post/delete/<int:post_id>', views.delete_post, name='delete-post'),
    path('category/<str:cat>/', views.category, name='posts-by-category'),
    # path('like/', views.like_post, name='like-post'),
    # path('like/<int:pk>', views.like_post_details, name='like-post-details'),
    path('like/', views.like, name='like'),
    path('setLikes/', views.set_likes, name='set_likes'),
    path('liked-by/<int:post_id>', views.liked_by, name='liked-by'),
    path('vouch/', views.vouch, name='vouch'),
    path('updateSession/', views.update_session, name='update_session'),
    path('getSessionData/', views.get_session_data, name='get_session_data'),

    path('fetch_replies_to_reply/', views.fetch_replies_to_reply,
         name='fetch_replies_to_reply'),
    # REST API views
    path('posts', views.post_list_view, name='post-list-view'),
    #     path('', views.home_view, name='home-page'),
    path('getPosts/', views.getPosts, name='get-posts-rest'),
    path('getPosts/<int:pk>', views.getPost, name='get-post-rest'),
    path('getPosts/<int:pk>/update', views.updatePost, name='update-post-rest'),
    path('getPosts/<int:pk>/delete', views.deletePost, name='delete-post-rest'),

    #     Communities section
    path('create_community', views.create_community, name='create-community'),
    path('edit_community/<int:id>',
         views.edit_community, name='edit-community'),
    path('edit_community_rules/<int:id>',
         views.editCommunityRules, name='edit_community_rules'),
    path('get_community_data/<int:id>',
         views.get_community_details, name='get_community_data'),
    path('community/<int:community_id>',
         views.community_page, name='community-page'),
    path('join_community', views.join_community, name='join_community'),
    path('add_post_community/<int:community_id>',
         views.add_post_community, name='add-post-community'),
    path('add_image_post_community/<int:community_id>',
         views.add_image_post_community, name='add-image-post-community'),
    path('add_video_post_community/<int:community_id>',
         views.add_video_post_community, name='add-video-post-community'),


    path('user/<str:user>', views.user_posts_page, name="user-posts-page"),
    path('user/profile/<str:user>', views.user_profile_stats,
         name="user-profile-stats"),

    path('create_gamer_profile/<str:user>',
         views.create_game_profile, name="create-gamer-profile"),
    path('edit_gamer_profile/<str:user>',
         views.edit_gamer_profile, name="edit-gamer-profile"),

    path('matchmaking/<str:user>', views.MatchmakingHome, name="matchmaking-home"),
    path('matchmaking_data/<str:user>',
         views.Matchmaking_Data, name="matchmaking-data"),

    path('getgamerank_server/<str:game>',
         views.get_game_rank_server, name="get-game-rank-server"),
    path('get_saved_gamerank_server/<str:game>',
         views.get_saved_game_rank_server, name="get-saved-game-rank-server"),
    path('start_following/<str:who_to_follow>',
         views.start_following, name="start-following"),
    path('search', views.search_results, name='search'),
    path('get_gamer_profile_stats/<str:user>',
         views.Gamer_Profile_Data, name="get-gamer-profile-data"),
    path('get_user_profile_stats/<str:user>/<str:game>',
         views.User_Profile_Page_Data, name='get-user-profile-data')
]

page3/models.py
from email.policy import default
from random import choices
from secrets import choice
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.core.validators import int_list_validator
from django.contrib.postgres.fields import ArrayField
from datetime import datetime, date
from ckeditor.fields import RichTextField
# from spacy import blank
import json

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=255, default="unnamed")
    tags = models.CharField(
        max_length=255, default='none')

    def save(self, *args, **kwargs):
        self.tags = self.name.replace(' ', '-').lower()
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('home-page')


class Community(models.Model):
    test=models.CharField(default="", null=True, max_length=10)
    name = models.CharField(max_length=255)
    bio = models.TextField(blank=True, null=True)
    profile_pic = models.ImageField(
        null=True, blank=True, upload_to="images/profile")
    community_header_pic = models.ImageField(
        null=True, blank=True, upload_to="images/profile")
    created_by = models.ForeignKey(
        User, on_delete=models.DO_NOTHING, default=None)
    members = models.ManyToManyField(
        User, default=None, blank=True, related_name='members')
    is_private = models.BooleanField(null=True, blank=True, default=False)
    community_admins = models.ManyToManyField(
        User, default=None, blank=True, related_name='community_admins')

    post_date = models.DateField(auto_now_add=True, null=True)
    post_datetime = models.DateTimeField(auto_now_add=True, null= True)
    rules = ArrayField(models.CharField(
        max_length=500, null=True, blank=True, default=""), blank=True, null=True, default=list)
    # post = models.ManyToManyField(
    #     Post, default=None, blank=True, related_name='community_posts')

    def __str__(self):
        return self.name


class Profile(models.Model):
    # This is User profile
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    bio = models.TextField(blank=True, null=True)
    profile_pic = models.ImageField(
        null=True, blank=True, upload_to="images/profile")
    discord_link = models.CharField(max_length=255, null=True, blank=True)
    twitch_link = models.CharField(max_length=255, null=True, blank=True)
    following = models.ManyToManyField(
        User, default=None, blank=True, related_name='following')
    followers = models.ManyToManyField(
        User, default=None, blank=True, related_name='followers')
    communities = models.ManyToManyField(
        Community, default=None, blank=True, related_name='communities')
    featured_communities = models.ManyToManyField(
        Community, default=None, blank=True, related_name='featuredCommunities')

    def __str__(self):
        return str(self.user)


empty_list = []


class Post(models.Model):
    title = models.CharField(max_length=255, blank=True, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

    # body = models.TextField()
    reply_to = models.IntegerField(null=True, blank=True, default=-1)
    is_reply = models.BooleanField(null=True, default=False, blank=True)
    is_parent_a_reply = models.BooleanField(
        null=True, default=False, blank=True)
    reply_root = models.IntegerField(null=True, blank=True, default=-1)
    post_date = models.DateField(auto_now_add=True, null=True)
    post_datetime = models.DateTimeField(auto_now_add=True, null=True)
    category = models.CharField(max_length=50, default='none', null=True)
    tags = models.CharField(
        max_length=255, default='', blank=True)
    likes = models.ManyToManyField(
        User, default=None, blank=True, related_name='posts')
    like_count = models.BigIntegerField(default='0')
    reply_count = models.BigIntegerField(default='0')
    video = models.FileField(null=True, blank=True, upload_to="videos/")
    has_images = models.BooleanField(null=True, blank=True, default=False)
    has_video = models.BooleanField(null=True, blank=True, default=False)
    user_profile = models.ForeignKey(
        Profile, on_delete=models.DO_NOTHING, default=None, null=True, blank=True,)
    body = models.CharField(max_length=280, blank=True, null=True)
    community = models.ForeignKey(
        Community, on_delete=models.DO_NOTHING, default=None, null=True, blank=True)
    images_ids_list = ArrayField(models.IntegerField(
        null=True, blank=True, default=-1), blank=True, null=True, default=list)
    images_urls_list = ArrayField(models.CharField(
        max_length=500, null=True, blank=True, default=""), blank=True, null=True, default=list)
    is_lft_lfp_post = models.BooleanField(null=True, default=False, blank=True)
    vouches = models.ManyToManyField(
        User, default=None, blank=True, related_name='vouches')
    vouch_count = models.BigIntegerField(default='0')

    def set_Tag(self, lst):
        self.tags = json.dumps(lst)

    def get_Tag(self):
        if self.tags:
            try:

                tag_list = json.loads(self.tags)
                return tag_list
            except ValueError as e:
                return ""

    def liked_by(self):
        likers = []
        for a in self.likes.all():
            likers.append(a.username)
        return likers

        return ', '.join([a.username for a in self.likes.all()])
        return self.likes.all()

    @property
    def num_likes(self):
        return self.likes.all().count()

    def total_likes(self):
        return self.likes.count()

    def save(self, *args, **kwargs):
        # self.tags = self.category.replace(' ', '-').lower()
        super(Post, self).save(*args, **kwargs)

    def __str__(self):
        return self.body + ' | ' + str(self.author) + '| ' + str(self.id) + ' | ' + str(self.is_reply)

    def get_absolute_url(self):
        return reverse('post-page', args=(str(self.post_id)))


class Tags(models.Model):
    tag_name = models.CharField(max_length=50, null=True)
    post = models.ManyToManyField(
        Post, default=None, blank=True, related_name='tagged_posts')

    def __str__(self):
        return self.tag_name


class Replies(models.Model):
    reply_to_post = models.ForeignKey(
        Post, on_delete=models.CASCADE, null=True, blank=True)
    reply_to = models.IntegerField(null=True, blank=True, default=-1)
    post_id = models.IntegerField(null=True, blank=True, default=-1)
    reply_root = models.IntegerField(null=True, blank=True, default=-1)

    def __str__(self):
        return 'Reply to: ' + str(self.reply_to) + ' | ' + 'Post id: ' + str(self.post_id) + ' | ' + 'reply root: ' + str(self.reply_root)


class ImageFiles(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, null=True, blank=True)
    image = models.FileField(null=True, blank=True, upload_to='images/')


LIKE_CHOICES = (
    ('Like', 'Like'),
    ('Unlike', 'Unlike'),
)


class GameProfile(models.Model):
    # This is User Game profile
    games_list = [('Valorant', 'Valorant'), ('Call of Duty', 'Call of Duty'),
                  ('League of Legends', 'League of Legends'), ('Counter Strike: GO', 'Counter Strike: GO')]

    class ValorantServers(models.TextChoices):
        APAC = 'APAC', 'Asia Pacific'
        EMEA = 'EMEA', 'Europe'
        NA = 'NA', 'North America'
        JA = 'JA', 'Japan'

    class CODServers(models.TextChoices):
        APAC = 'APAC', 'Asia Pacific'
        EMEA = 'EMEA', 'Europe'
        NA = 'NA', 'North America'

    class LOLServers(models.TextChoices):
        APAC = 'APAC', 'Asia Pacific'
        EMEA = 'EMEA', 'Europe'
        NA = 'NA', 'North America'

    class CSServers(models.TextChoices):
        EMEA = 'EMEA', 'Europe'
        NA = 'NA', 'North America'

    class ValorantRanks(models.TextChoices):
        Iron = 'IRON', 'Iron :((('
        Bronze = 'Bronze', 'Bronze :(('
        Silver = 'Silver', 'Silver :('
        Gold = 'Gold', 'Gold :('
        Platinum = 'Platinum', 'Platinum '
        Diamond = 'Diamond', 'Diamond :) '
        Asencdant = 'Asencdant', 'Asencdant :)) '
        Immortal = 'Immortal', 'Immortal >_< '
        Radiant = 'Radiant', 'Radiant :> '

    class LOLRanks(models.TextChoices):
        Iron = 'IRON', 'Iron :((('
        Bronze = 'Bronze', 'Bronze :(('
        Silver = 'Silver', 'Silver :('
        Gold = 'Gold', 'Gold :('
        Platinum = 'Platinum', 'Platinum '
        Diamond = 'Diamond', 'Diamond :) '
        Master = 'Master', 'Master :)) '
        Grandmaster = 'Grandmaster', 'Grandmaster >_< '
        Challenger = 'Challenger', 'Challenger :> '

    class CODRanks(models.TextChoices):
        Rookie = 'Rookie', 'Rookie :((('
        Veteran = 'Veteran', 'Veteran :(('
        Elite = 'Elite', 'Elite :('
        Pro = 'Pro', 'Pro :('
        Master = 'Master', 'Master '
        Grandmaster = 'Grandmaster', 'Grandmaster :) '
        Legendary = 'Legendary', 'Legendary :)) '

    class CSRanks(models.TextChoices):

        Silver = 'Silver', 'Silver :('
        Gold = 'Gold', 'Gold :('
        Master_Guardian = 'Master Guardian', 'Master Guardian '
        Distinguished_Master_Guardian = 'Distinguished Master Guardian', 'Distinguished Master Guardian :) '
        Legendary = 'Legendary', 'Legendary :)) '
        Elite = 'Elite', 'Elite >_< '

    class User_Status(models.TextChoices):
        LFTeams = 'Looking for teams', 'Looking for teams'
        LFTalent = 'Looking for talent', 'Looking for talent'
        none = 'none', 'none'

    # Adding or changing fields here requires changes in views.py
    experience_fields = ['Team/ Org Name', 'Role/ Experience']

    games_logo_list = {'League of Legends': '/media/images/logos/LoL_icon.svg.png',

page3/templates/post/replies/replies_list.html
{% load static %}

{% block content %}

<br />


{% if replies_to_post %}


{% for post in replies_to_post %}
<div class="post">

    {% include 'post/postElement/post_content_section.html' %}

    <!--  -->

    {% if user.profile.id %}

    <button id="like-button" class="like-button" name="{{ post.like_count }}"
        value="{{ post.id }}">{{post.like_count}}<i class="fa-solid fa-heart"></i>
    </button>

    <button id="open-reply-modal" class="reply-button" value="{{post.pk}}">{{post.reply_count}}<i
            class="fa-solid fa-comment"></i></button>



    {% endif %}

    {% if show_replies_button %}
    {% if post.reply_count > 0 %}

    {% if post.reply_count == 1 %}
    <button class="show-replies-btn" id="show-replies" value="{{post.pk}}"
        onclick="this.innerHTML=toggleReplies(this.innerHTML)">Show Reply</button>
    {% else %}

    <button class="show-replies-btn" id="show-replies" value="{{post.pk}}"
        onclick="this.innerHTML=toggleReplies(this.innerHTML)">Show {{ post.reply_count }} Replies</button>
    {% endif %}




    {% endif %}


    {% else %}
    {% endif %}
    <div class="replies-holder" id="replies-holder" value="{{post.pk}}" style="display: none;">

    </div>

    <hr>

</div>
{% endfor %}
{% endif %}

<br /><br />

<br />

<button onclick="history.go(-1)">Back</button>
<!-- <a href="{% url 'home-page'  %}">Back</a> -->




{% endblock content %}

page3/templates/post/replies/replies_page.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}
Page3 - Replies
{% endblock title %}

{% block content %}
{% load crispy_forms_tags %}


{% include 'navigation/navbar-top.html' %}
<div class="main-body">

    {% include 'navigation/sidebar-left.html' %}
    <div class="page-contents">

        <div class="posts-timeline">
            {% include 'post/postElement/post_element_replies.html' %}
            <div id="replies-section">
                {% include 'post/replies/replies_list.html' %}
            </div>
        </div>
        {% include 'navigation/sidebar.html' %}
    </div>
</div>

<!-- JS Scripts Here -->

<script>


    function updateText(btn, no_of_likes) {
        //btn.element.innerHTML = "LIKED BY" + " " + no_of_likes + "lkl"
        //btn.text("LIKED BY" + " " + no_of_likes + " <h1>JLO</h1>")
        elem = "<i class='fa-solid fa-heart'></i>"
        btn[0].innerHTML = no_of_likes + elem
        console.log(btn[0].innerHTML)
    }
    $(document).on('click', '#like-button', function (e) {
        e.preventDefault();

        var this_ = $(this)
        postid = this_.attr("value").valueOf()



        $.ajax({
            type: 'POST',
            url: '{% url "like" %}',
            data: {
                postid: postid,
                // postid: $('#like-button').val(),
                action: 'post',
            },
            success: function (json) {
                no_of_likes = json['result'];
                console.log(json)
                updateText(this_, no_of_likes)
            },
            error: function (xhr, errmsg, err) {

            }
        });
    })


</script>

<script>
    function updateText(btn, no_of_likes) {
        //btn.element.innerHTML = "LIKED BY" + " " + no_of_likes + "lkl"
        //btn.text("LIKED BY" + " " + no_of_likes + " <h1>JLO</h1>")
        elem = "<i class='fa-solid fa-heart'></i>"
        btn[0].innerHTML = no_of_likes + elem
        console.log(btn[0].innerHTML)
    }
    function updateLikes() {

        let allLikes = document.getElementsByClassName('like-button');


        for (let i = 0; i < allLikes.length; i++) {
            let attributeValue = allLikes[i].getAttribute('value');
            console.log(typeof allLikes[i])
            console.log(attributeValue)

            $.ajax({
                type: 'POST',
                url: '{% url "set_likes" %}',
                data: {
                    postid: attributeValue,
                    // postid: $('#like-button').val(),
                    action: 'post',
                    // postid: '{{ post.pk }}',
                },
                success: function (json) {
                    no_of_likes = json['result'];
                    //console.log(json)
                    //updateText(allLikes[i], no_of_likes)
                    allLikes[i].innerHTML = "LIKED BY" + " " + no_of_likes
                    console.log("AJAX REQUEST")
                },
                error: function (response) {

                }
            });


        }
        console.log(allLikes)

    }

    const xhr = new XMLHttpRequest()
    const method = 'GET'
    const url = "/posts"
    const responseType = 'json'

    xhr.responseType = responseType
    xhr.open(method, url)
    xhr.onload = function () {
        var listedItems = xhr.response.response
        console.log(listedItems)
    }
</script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript">
    // form upload

    const modalContainer = document.getElementById("reply-modal-container");
    const close = document.getElementById("close-modal");


    $(document).on('click', '#open-reply-modal', function (e) {
        var this_ = $(this);
        postid = this_.attr("value").valueOf();
        console.log("POSTID: " + postid)
        modalContainer.classList.add('show');
    });




    close.addEventListener('click', () => {
        modalContainer.classList.remove('show');
    });


    $('#id_ajax_upload_form').submit(function (e) {
        e.preventDefault();
        $form = $(this)
        var formData = new FormData(this);

        //var this_ = $(this)
        //postid = this_.attr("value").valueOf()
        formData.append('postid', postid)
        $.ajax({
            url: window.location.pathname,
            type: 'POST',
            data: formData,

            success: function (response) {
                //alert("JKJJK")
                $("#replies-section").html(response['replies_list']);
                $("#id_title").val('');
                $("#id_body").val('');
                $("#id_image").val('');
                //console.log($("#id_image").val())
                //$("#id_category").val('');
                modalContainer.classList.remove('show');
            },
            cache: false,
            contentType: false,
            processData: false
        });
    });

    $('#id_ajax_upload_form2').submit(function (e) {
        e.preventDefault();
        $form = $(this)
        var formData = new FormData(this);
        //var this_ = $(this)
        //postid = this_.attr("value").valueOf()
        formData.append('postid', postid)
        $.ajax({
            url: window.location.pathname,
            type: 'POST',
            data: formData,
            success: function (response) {
                //alert("JKJJK")
                $("#replies-section").html(response['replies_list']);
                $("#id_title").val('');
                $("#id_body").val('');
                $("#id_video").val('');
                //console.log($("#id_image").val())
                //$("#id_category").val('');
                modalContainer.classList.remove('show');
            },
            cache: false,
            contentType: false,
            processData: false
        });
    });
    // end
</script>

<script>
    window.addEventListener("pageshow", hideVidForm);

    function hideVidForm() {
        document.getElementById("vid-form").style.display = 'none';
    }


    document.getElementById('toggle-media-type').addEventListener('click', function () {
        let elem = document.getElementById('toggle-media-type');
        form1 = document.getElementById("img-form")
        form2 = document.getElementById("vid-form")
        if (elem.innerHTML == "Add video") {
            elem.innerHTML = "Add images";

            form1.style.display = 'none';
            form2.style.display = 'block';
        }
        else {
            elem.innerHTML = "Add video";
            form1.style.display = 'block';
            form2.style.display = 'none';
        }

    })
</script>

<script>
    $(document).on('click', '#show-replies', function (e) {
        e.preventDefault();

        var this_ = $(this)
        postid = this_.attr("value").valueOf()



        $.ajax({
            type: 'POST',
            url: '{% url "fetch_replies_to_reply" %}',
            data: {
                postid: postid,
                // postid: $('#like-button').val(),
                action: 'post',
            },
            success: function (json) {

                console.log(json['replies_list'])
                let repliesHolders = document.getElementsByClassName('replies-holder');
                for (let i = 0; i < repliesHolders.length; i++) {
                    let attributeValue = repliesHolders[i].getAttribute('value');
                    console.log(typeof repliesHolders[i])
                    console.log(typeof attributeValue)
                    console.log(attributeValue)
                    if (postid === attributeValue) {
                        console.log("This one!")
                        let elem = repliesHolders[i];
                        var child = elem.lastElementChild;
                        while (child) {
                            elem.removeChild(child);
                            child = elem.lastElementChild;
                        }
                        //var repliesList = document.createElement("div")
                        //repliesList.id = "replies-div"
                        //$("#replies-div").innerHTML = "Yahallo"
                        //console.log($('#replies-div').text())
                        elem = repliesHolders[i]
                        var id = 'replyTo' + postid

                        elem.setAttribute('id', id)

                        $("#" + id).html(json['replies_list'])

                        var div = document.getElementById(id)
                        console.log("DIVV:", div)
                        if (div.style.display === "none") {
                            div.style.display = "block"
                            console.log("THIS: ", this_)
                            console.log()

                        }
                        else {
                            div.style.display = "none"
                        }


                        //elem.html(json['replies_list']);

                        //$("#replies-holder").html(json['replies_list']);
                        //repliesList.html(json['replies_list'])
                        //elem.appendChild(repliesList)

                    }
                }

            },
            error: function (xhr, errmsg, err) {

            }
        });
    });
</script>

<script>
    function toggleReplies(e) {


        if (e.includes("Show")) {
            return e.replace("Show", "Hide")
        }
        else {
            return e.replace("Hide", "Show")
        }
    }
</script>

{% endblock content %}

page3/templates/post/replies/reply_reply_form.html
<div id="img-form">
    <form enctype="multipart/form-data" id="id_ajax_upload_form3" method="POST" novalidate="" value="{{reply.pk}}">
        {% csrf_token %}
        {% for field in form1 %}
        {{ field }}<br />
        {% endfor %}

        {{ imageform.management_form }}

        {% for field in imageform %}
        {{ field }}
        {% endfor %}
        <input type="submit" />
    </form>
</div>

<div id="vid-form">
    <form enctype="multipart/form-data" id="id_ajax_upload_form4" method="POST" novalidate="" value="{{reply.pk}}">
        {% csrf_token %}
        {{ form2.as_p }}
        <input type="submit" />
    </form>
</div>
<button id="toggle-media-type">Add video</button>